#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require './lib/lexer'
  require './lib/ast'


module Koona
  class Parser < Racc::Parser

module_eval(<<'...end koona.y/module_eval...', 'koona.y', 73)
  def on_error(tok, val, vstack)
    $stderr.puts "#{val.filename}:#{val.lineno} Parse error on value: \"#{val.value}\"", "Stack: #{vstack.inspect}"
  end
  def parse(tokens)
    @tokens = tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end koona.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    15,    17,    16,    18,    15,    17,    16,    18,    15,    63,
    42,    24,    64,    11,    60,    24,    15,    61,    41,    42,
    47,    14,    13,    15,    19,    20,    50,    51,    19,    20,
    15,    17,    16,    18,    15,    17,    16,    18,    43,    11,
    11,    24,    15,    11,    25,    24,    15,   nil,   nil,   nil,
   nil,    14,    13,   nil,    19,    20,   nil,   nil,    19,    20,
    15,    17,    16,    18,    15,    17,    16,    18,   nil,   nil,
   nil,    24,   nil,    11,    39,    24,    15,    17,    16,    18,
   nil,    14,    13,   nil,    19,    20,   nil,    24,    19,    20,
   nil,    15,    17,    16,    18,    15,    17,    16,    18,   nil,
    19,    20,    24,   nil,   nil,   nil,    24,    15,    17,    16,
    18,   nil,   nil,   nil,   nil,    19,    20,   nil,    24,    19,
    20,   nil,    15,    17,    16,    18,    15,    17,    16,    18,
   nil,    19,    20,    24,   nil,    11,    49,    24,   nil,   nil,
   nil,   nil,   nil,    14,    13,   nil,    19,    20,   nil,   nil,
    19,    20,    28,    29,    30,    31,    32,    33,   nil,   nil,
    62,   nil,   nil,   nil,   nil,    34,    35,    36,    37,    28,
    29,    30,    31,    32,    33,    28,    29,    30,    31,    32,
    33,   nil,    34,    35,    36,    37,   nil,   nil,    34,    35,
    36,    37,    28,    29,    30,    31,    32,    33,    28,    29,
    30,    31,    32,    33,   nil,    34,    35,    36,    37,   nil,
   nil,    34,    35,    36,    37,    28,    29,    30,    31,    32,
    33,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    34,    35,
    36,    37,    28,    29,    30,    31,    32,    33,   nil,   nil,
    56,   nil,   nil,   nil,   nil,    34,    35,    36,    37,    28,
    29,    30,    31,    32,    33,    28,    29,    30,    31,    32,
    33,   nil,    34,    35,    36,    37,   nil,   nil,    34,    35,
    36,    37 ]

racc_action_check = [
     0,     0,     0,     0,    43,    43,    43,    43,    12,    58,
    45,     0,    58,     0,    53,    43,    51,    53,    12,    12,
    25,     0,     0,    59,     0,     0,    40,    40,    43,    43,
     2,     2,     2,     2,    42,    42,    42,    42,    13,    62,
    63,     2,    64,     2,     1,    42,    69,   nil,   nil,   nil,
   nil,     2,     2,   nil,     2,     2,   nil,   nil,    42,    42,
    11,    11,    11,    11,    41,    41,    41,    41,   nil,   nil,
   nil,    11,   nil,    11,    11,    41,    61,    61,    61,    61,
   nil,    11,    11,   nil,    11,    11,   nil,    61,    41,    41,
   nil,    14,    14,    14,    14,    24,    24,    24,    24,   nil,
    61,    61,    14,   nil,   nil,   nil,    24,    50,    50,    50,
    50,   nil,   nil,   nil,   nil,    14,    14,   nil,    50,    24,
    24,   nil,    38,    38,    38,    38,    27,    27,    27,    27,
   nil,    50,    50,    38,   nil,    38,    38,    27,   nil,   nil,
   nil,   nil,   nil,    38,    38,   nil,    38,    38,   nil,   nil,
    27,    27,    55,    55,    55,    55,    55,    55,   nil,   nil,
    55,   nil,   nil,   nil,   nil,    55,    55,    55,    55,    52,
    52,    52,    52,    52,    52,     5,     5,     5,     5,     5,
     5,   nil,    52,    52,    52,    52,   nil,   nil,     5,     5,
     5,     5,    66,    66,    66,    66,    66,    66,    44,    44,
    44,    44,    44,    44,   nil,    66,    66,    66,    66,   nil,
   nil,    44,    44,    44,    44,    57,    57,    57,    57,    57,
    57,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    57,    57,
    57,    57,    46,    46,    46,    46,    46,    46,   nil,   nil,
    46,   nil,   nil,   nil,   nil,    46,    46,    46,    46,    48,
    48,    48,    48,    48,    48,    54,    54,    54,    54,    54,
    54,   nil,    48,    48,    48,    48,   nil,   nil,    54,    54,
    54,    54 ]

racc_action_pointer = [
    -2,    44,    28,   nil,   nil,   169,   nil,   nil,   nil,   nil,
   nil,    58,     6,    25,    89,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    93,    20,   nil,   124,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   120,   nil,
    14,    62,    32,     2,   192,    -3,   226,   nil,   243,   nil,
   105,    14,   163,     0,   249,   146,   nil,   209,    -5,    21,
   nil,    74,    24,    25,    40,   nil,   186,   nil,   nil,    44,
   nil ]

racc_action_default = [
   -48,   -48,    -1,    -2,    -4,    -5,    -6,    -7,    -8,    -9,
   -10,   -48,   -31,   -48,   -20,   -22,   -23,   -24,   -25,   -26,
   -27,   -28,   -29,   -30,   -48,   -48,    -3,   -48,   -38,   -39,
   -40,   -41,   -42,   -43,   -44,   -45,   -46,   -47,   -48,   -11,
   -48,   -48,   -35,   -48,   -21,   -31,   -48,    71,   -33,   -12,
   -48,   -17,   -14,   -48,   -36,   -48,   -34,   -13,   -48,   -48,
   -32,   -48,   -48,   -48,   -48,   -18,   -37,   -15,   -16,   -48,
   -19 ]

racc_goto_table = [
    12,    26,    12,    44,     2,    67,    68,     1,    58,    53,
   nil,    12,    40,    46,   nil,    38,    48,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    52,    54,    55,   nil,   nil,   nil,   nil,    26,    12,    57,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    66,    59,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    65,
   nil,   nil,   nil,   nil,    69,   nil,   nil,   nil,   nil,    70 ]

racc_goto_check = [
    11,     3,    11,     5,     2,     6,     6,     1,    12,    16,
   nil,    11,    11,     5,   nil,     2,     5,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     5,     5,     5,   nil,   nil,   nil,   nil,     3,    11,     5,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     5,    11,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,
   nil,   nil,   nil,   nil,    11,   nil,   nil,   nil,   nil,    11 ]

racc_goto_pointer = [
   nil,     7,     4,    -1,   nil,   -11,   -57,   nil,   nil,   nil,
   nil,     0,   -43,   nil,   nil,   nil,   -33,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    45,   nil,    21,    22,    23,   nil,    27 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 29, :_reduce_1,
  1, 30, :_reduce_2,
  2, 30, :_reduce_3,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  2, 34, :_reduce_11,
  3, 34, :_reduce_12,
  4, 36, :_reduce_13,
  3, 37, :_reduce_14,
  5, 38, :_reduce_15,
  6, 35, :_reduce_16,
  0, 40, :_reduce_17,
  2, 40, :_reduce_18,
  4, 40, :_reduce_19,
  1, 32, :_reduce_20,
  2, 32, :_reduce_21,
  1, 39, :_reduce_22,
  1, 41, :_reduce_23,
  1, 41, :_reduce_24,
  1, 42, :_reduce_25,
  1, 43, :_reduce_26,
  1, 43, :_reduce_27,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  4, 33, :_reduce_32,
  3, 33, :_reduce_33,
  3, 33, :_reduce_34,
  0, 44, :_reduce_35,
  1, 44, :_reduce_36,
  3, 44, :_reduce_37,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none,
  1, 45, :_reduce_none ]

racc_reduce_n = 48

racc_shift_n = 71

racc_token_table = {
  false => 0,
  :error => 1,
  :TIDENTIFIER => 2,
  :TDOUBLE => 3,
  :TINTEGER => 4,
  :TSTRING => 5,
  :TCEQ => 6,
  :TCNE => 7,
  :TCLT => 8,
  :TCLE => 9,
  :TCGT => 10,
  :TCGE => 11,
  :TEQUAL => 12,
  :TLPAREN => 13,
  :TRPAREN => 14,
  :TLBRACE => 15,
  :TRBRACE => 16,
  :TCOMMA => 17,
  :TDOT => 18,
  :TPLUS => 19,
  :TMINUS => 20,
  :TMUL => 21,
  :TDIV => 22,
  :TRETURN => 23,
  :TIF => 24,
  :TELSE => 25,
  :TTRUE => 26,
  :TFALSE => 27 }

racc_nt_base = 28

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TIDENTIFIER",
  "TDOUBLE",
  "TINTEGER",
  "TSTRING",
  "TCEQ",
  "TCNE",
  "TCLT",
  "TCLE",
  "TCGT",
  "TCGE",
  "TEQUAL",
  "TLPAREN",
  "TRPAREN",
  "TLBRACE",
  "TRBRACE",
  "TCOMMA",
  "TDOT",
  "TPLUS",
  "TMINUS",
  "TMUL",
  "TDIV",
  "TRETURN",
  "TIF",
  "TELSE",
  "TTRUE",
  "TFALSE",
  "$start",
  "program",
  "stmts",
  "stmt",
  "return_stmt",
  "expr",
  "block",
  "func_decl",
  "var_decl",
  "var_assign",
  "if_stmt",
  "ident",
  "func_decl_args",
  "numeric",
  "string",
  "bool",
  "call_args",
  "binop" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'koona.y', 10)
  def _reduce_1(val, _values, result)
    result = Koona::AST::NBlock.new(Koona::AST::NStatementList.new); result.statementlist.statements << val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 11)
  def _reduce_2(val, _values, result)
    result = Koona::AST::NStatementList.new; result.statements << val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 12)
  def _reduce_3(val, _values, result)
    val[0].statements << val[1]
    result
  end
.,.,

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'koona.y', 22)
  def _reduce_11(val, _values, result)
    result = Koona::AST::NBlock.new
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 23)
  def _reduce_12(val, _values, result)
    result = Koona::AST::NBlock.new(Koona::AST::NStatementList.new); result.statementlist.statements << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 25)
  def _reduce_13(val, _values, result)
    result = Koona::AST::NVariableDeclaration.new(val[0], val[1], val[3], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 27)
  def _reduce_14(val, _values, result)
    result = Koona::AST::NVariableAssignment.new(val[0], val[2], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 29)
  def _reduce_15(val, _values, result)
    result = Koona::AST::NIf.new(val[2], val[4], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 32)
  def _reduce_16(val, _values, result)
    result = Koona::AST::NFunctionDeclaration.new(val[0], val[1], val[3], val[5], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 34)
  def _reduce_17(val, _values, result)
    result = Koona::AST::VariableList.new
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 35)
  def _reduce_18(val, _values, result)
    result = Koona::AST::VariableList.new; result.variables << Koona::AST::FunctionVar.new(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 36)
  def _reduce_19(val, _values, result)
    val[0].variables << Koona::AST::FunctionVar.new(val[2], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 37)
  def _reduce_20(val, _values, result)
    result = Koona::AST::NReturn.new(nil, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 38)
  def _reduce_21(val, _values, result)
    result = Koona::AST::NReturn.new(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 40)
  def _reduce_22(val, _values, result)
    result = Koona::AST::NIdentifier.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 42)
  def _reduce_23(val, _values, result)
    result = Koona::AST::NInteger.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 43)
  def _reduce_24(val, _values, result)
    result = Koona::AST::NFloat.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 45)
  def _reduce_25(val, _values, result)
    result = Koona::AST::NString.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 47)
  def _reduce_26(val, _values, result)
    result = Koona::AST::NBool.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 48)
  def _reduce_27(val, _values, result)
    result = Koona::AST::NBool.new(val[0])
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

module_eval(<<'.,.,', 'koona.y', 54)
  def _reduce_32(val, _values, result)
    result = Koona::AST::NFunctionCall.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 55)
  def _reduce_33(val, _values, result)
    result = Koona::AST::NBinaryOperator.new(val[0], val[1], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 56)
  def _reduce_34(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 58)
  def _reduce_35(val, _values, result)
    result = Koona::AST::VariableList.new
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 59)
  def _reduce_36(val, _values, result)
    result = Koona::AST::VariableList.new; result.variables << val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'koona.y', 60)
  def _reduce_37(val, _values, result)
    val[0].variables << val[2]
    result
  end
.,.,

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Koona
